# Generated by Django 3.2.7 on 2022-01-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Drama', 'Drama'), ('ACTION', 'ACTION')], max_length=6)),
            ],
            options={
                'verbose_name': 'Listings',
                'verbose_name_plural': 'Listings',
            },
        ),
    ]
