# Generated by Django 3.2.7 on 2022-02-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=20)),
                ('gas_price_km3', models.IntegerField()),
                ('co2_coefficient', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
